limit:
  default:
    totem: 4
    shulker: 4
  vip:
    totem: 6
    shulker: 6
  admin:
    totem: 0 # 0 = лимита нет
    shulker: 0 # 0 = лимита нет

messages:
  totem: "&fУ вас &eтотемов &a%totem% &fиз &c%totem_max%"
  shulker: "&fУ вас &dшалкеров &a%shulker% &fиз &c%shulker_max%"
  no-permission: "&cНет прав!"